base.url = https://xiaomi.kg/
//base.url = https://www.ebay.com/
//base.url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
base.url = https://mashina.kg/
gorest.base.url = https://gorest.co.in/
//gorest.postBase.url = https://gorest.co.in/public/v2/posts/
bearer.token = 837f845e266e6cfd75513b82a9ba206c257deda0e5890062b23140fb6112f88b
server = localhost
port = 5432
user = postgres